//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllThingsDelivered.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AllThingsDeliveredDBEntities : DbContext
    {
        public AllThingsDeliveredDBEntities()
            : base("name=AllThingsDeliveredDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomOrderContent> CustomOrderContents { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<OrderContent> OrderContents { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<RestaurantCategory> RestaurantCategories { get; set; }
        public virtual DbSet<RestaurantItem> RestaurantItems { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
    }
}
