//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllThingsDelivered.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartContent
    {
        public int CartContentID { get; set; }
        public int CustomerID { get; set; }
        public int RestaurantID { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Customize { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
