//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllThingsDelivered.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.CustomOrderContents = new HashSet<CustomOrderContent>();
            this.OrderContents = new HashSet<OrderContent>();
        }
    
        public int OrderID { get; set; }
        public int AddressID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime TimePlaced { get; set; }
        public bool Active { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<decimal> DeliveryFee { get; set; }
        public Nullable<decimal> Customertip { get; set; }
        public Nullable<int> DriverRating { get; set; }
        public string Customize { get; set; }
        public string PaymentToken { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomOrderContent> CustomOrderContents { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderContent> OrderContents { get; set; }
    }
}
