//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllThingsDelivered.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantItem
    {
        public int RestaurantItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public int RestaurantID { get; set; }
        public Nullable<int> RestaurantCategoryID { get; set; }
    
        public virtual RestaurantCategory RestaurantCategory { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
